/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/reaction.1.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ReactionModel(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/reaction.1.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="BezierCircle" rotation={[Math.PI / 4, 0, 0]} />
				<group name="BezierCircle001" rotation={[-0.26, 0, 0]} />
				<group name="BezierCircle002" rotation={[1.82, 0, 0]} />
				<group name="Icosphere">
					<mesh
						name="Sphere"
						geometry={nodes.Sphere.geometry}
						material={materials["Material.001"]}
						position={[0.12, -1.23, 0.37]}
						rotation={[2.9, 0.67, -0.13]}
					/>
					<mesh
						name="Sphere_1"
						geometry={nodes.Sphere_1.geometry}
						material={materials["Material.001"]}
						position={[0.91, -0.83, 0.38]}
						rotation={[0.15, -0.48, -2.23]}
					/>
					<mesh
						name="Sphere_2"
						geometry={nodes.Sphere_2.geometry}
						material={materials["Material.001"]}
						position={[-0.31, -1.23, 0.23]}
						rotation={[0.49, 1.16, 2.41]}
					/>
					<mesh
						name="Sphere_3"
						geometry={nodes.Sphere_3.geometry}
						material={materials["Material.001"]}
						position={[-0.31, -1.23, -0.23]}
						rotation={[0.19, -0.05, 2.87]}
					/>
					<mesh
						name="Sphere_4"
						geometry={nodes.Sphere_4.geometry}
						material={materials["Material.001"]}
						position={[0.12, -1.23, -0.37]}
						rotation={[0.64, -1.25, -2.81]}
					/>
					<mesh
						name="Sphere_5"
						geometry={nodes.Sphere_5.geometry}
						material={materials["Material.001"]}
						position={[1.15, -0.44, 0.38]}
						rotation={[1.51, -0.36, -1.32]}
					/>
					<mesh
						name="Sphere_6"
						geometry={nodes.Sphere_6.geometry}
						material={materials["Material.001"]}
						position={[-0.01, -0.44, 1.21]}
						rotation={[1.9, -0.16, -0.03]}
					/>
					<mesh
						name="Sphere_7"
						geometry={nodes.Sphere_7.geometry}
						material={materials["Material.001"]}
						position={[-1.16, -0.44, 0.37]}
						rotation={[1.84, 0.26, 1.17]}
					/>
					<mesh
						name="Sphere_8"
						geometry={nodes.Sphere_8.geometry}
						material={materials["Material.001"]}
						position={[-0.71, -0.44, -0.99]}
						rotation={[1.39, 0.33, 2.49]}
					/>
					<mesh
						name="Sphere_9"
						geometry={nodes.Sphere_9.geometry}
						material={materials["Material.001"]}
						position={[0.72, -0.44, -0.98]}
						rotation={[1.21, -0.06, -2.58]}
					/>
					<mesh
						name="Sphere_10"
						geometry={nodes.Sphere_10.geometry}
						material={materials["Material.001"]}
						position={[1.03, -0.2, 0.75]}
						rotation={[2.47, 0.44, -1.09]}
					/>
					<mesh
						name="Sphere_11"
						geometry={nodes.Sphere_11.geometry}
						material={materials["Material.001"]}
						position={[-0.39, -0.2, 1.21]}
						rotation={[1.25, 0.94, 0.54]}
					/>
					<mesh
						name="Sphere_12"
						geometry={nodes.Sphere_12.geometry}
						material={materials["Material.001"]}
						position={[-1.28, -0.2, 0]}
						rotation={[0.6, 0.07, 1.67]}
					/>
					<mesh
						name="Sphere_13"
						geometry={nodes.Sphere_13.geometry}
						material={materials["Material.001"]}
						position={[-0.39, -0.2, -1.21]}
						rotation={[1.05, -0.87, 2.65]}
					/>
					<mesh
						name="Sphere_14"
						geometry={nodes.Sphere_14.geometry}
						material={materials["Material.001"]}
						position={[1.03, -0.2, -0.75]}
						rotation={[2.41, -0.57, -1.87]}
					/>
					<mesh
						name="Sphere_15"
						geometry={nodes.Sphere_15.geometry}
						material={materials["Material.001"]}
						position={[0.51, 0.83, 0.85]}
						rotation={[1.03, 0.54, -0.5]}
					/>
					<mesh
						name="Sphere_16"
						geometry={nodes.Sphere_16.geometry}
						material={materials["Material.001"]}
						position={[-0.64, 0.83, 0.75]}
						rotation={[0.87, -0.26, 0.51]}
					/>
					<mesh
						name="Sphere_17"
						geometry={nodes.Sphere_17.geometry}
						material={materials["Material.001"]}
						position={[-0.91, 0.83, -0.38]}
						rotation={[1.64, -0.74, 1.89]}
					/>
					<mesh
						name="Sphere_18"
						geometry={nodes.Sphere_18.geometry}
						material={materials["Material.001"]}
						position={[0.08, 0.83, -0.99]}
						rotation={[2.3, -0.16, -3.1]}
					/>
					<mesh
						name="Sphere_19"
						geometry={nodes.Sphere_19.geometry}
						material={materials["Material.001"]}
						position={[0.96, 0.83, -0.23]}
						rotation={[2.02, 0.62, -2.05]}
					/>
					<mesh
						name="Sphere_20"
						geometry={nodes.Sphere_20.geometry}
						material={materials["Material.001"]}
						position={[0.31, 1.23, -0.23]}
						rotation={[2.6, 0.87, -2.71]}
					/>
					<mesh
						name="Sphere_21"
						geometry={nodes.Sphere_21.geometry}
						material={materials["Material.001"]}
						position={[0.63, 1.02, -0.46]}
						rotation={[0.58, 0.98, -1.08]}
					/>
					<mesh
						name="Sphere_22"
						geometry={nodes.Sphere_22.geometry}
						material={materials["Material.001"]}
						position={[0.51, 0.83, -0.85]}
						rotation={[2.11, 0.54, -2.64]}
					/>
					<mesh
						name="Sphere_23"
						geometry={nodes.Sphere_23.geometry}
						material={materials["Material.001"]}
						position={[-0.12, 1.23, -0.37]}
						rotation={[2.79, -0.3, 3.03]}
					/>
					<mesh
						name="Sphere_24"
						geometry={nodes.Sphere_24.geometry}
						material={materials["Material.001"]}
						position={[-0.24, 1.02, -0.74]}
						rotation={[2.7, 0.78, 2.88]}
					/>
					<mesh
						name="Sphere_25"
						geometry={nodes.Sphere_25.geometry}
						material={materials["Material.001"]}
						position={[-0.64, 0.83, -0.75]}
						rotation={[2.28, -0.26, 2.63]}
					/>
					<mesh
						name="Sphere_26"
						geometry={nodes.Sphere_26.geometry}
						material={materials["Material.001"]}
						position={[-0.39, 1.23, 0]}
						rotation={[Math.PI / 2, -1.23, Math.PI / 2]}
					/>
					<mesh
						name="Sphere_27"
						geometry={nodes.Sphere_27.geometry}
						material={materials["Material.001"]}
						position={[-0.78, 1.02, 0]}
						rotation={[2.8, -0.41, 2.42]}
					/>
					<mesh
						name="Sphere_28"
						geometry={nodes.Sphere_28.geometry}
						material={materials["Material.001"]}
						position={[-0.91, 0.83, 0.38]}
						rotation={[1.5, -0.74, 1.25]}
					/>
					<mesh
						name="Sphere_29"
						geometry={nodes.Sphere_29.geometry}
						material={materials["Material.001"]}
						position={[-0.12, 1.23, 0.37]}
						rotation={[0.35, -0.3, 0.11]}
					/>
					<mesh
						name="Sphere_30"
						geometry={nodes.Sphere_30.geometry}
						material={materials["Material.001"]}
						position={[-0.24, 1.02, 0.74]}
						rotation={[1.22, -1.24, 0.62]}
					/>
					<mesh
						name="Sphere_31"
						geometry={nodes.Sphere_31.geometry}
						material={materials["Material.001"]}
						position={[0.08, 0.83, 0.99]}
						rotation={[0.84, -0.16, -0.04]}
					/>
					<mesh
						name="Sphere_32"
						geometry={nodes.Sphere_32.geometry}
						material={materials["Material.001"]}
						position={[0.31, 1.23, 0.23]}
						rotation={[0.54, 0.87, -0.43]}
					/>
					<mesh
						name="Sphere_33"
						geometry={nodes.Sphere_33.geometry}
						material={materials["Material.001"]}
						position={[0.63, 1.02, 0.46]}
						rotation={[Math.PI / 10, -0.19, -0.52]}
					/>
					<mesh
						name="Sphere_34"
						geometry={nodes.Sphere_34.geometry}
						material={materials["Material.001"]}
						position={[0.96, 0.83, 0.23]}
						rotation={[1.12, 0.62, -1.09]}
					/>
					<mesh
						name="Sphere_35"
						geometry={nodes.Sphere_35.geometry}
						material={materials["Material.001"]}
						position={[1.16, 0.44, -0.37]}
						rotation={[2.71, -0.17, -2.02]}
					/>
					<mesh
						name="Sphere_36"
						geometry={nodes.Sphere_36.geometry}
						material={materials["Material.001"]}
						position={[1.02, 0.24, -0.74]}
						rotation={[1.68, 0.15, -2.21]}
					/>
					<mesh
						name="Sphere_37"
						geometry={nodes.Sphere_37.geometry}
						material={materials["Material.001"]}
						position={[0.71, 0.44, -0.99]}
						rotation={[2.52, -0.63, -2.35]}
					/>
					<mesh
						name="Sphere_38"
						geometry={nodes.Sphere_38.geometry}
						material={materials["Material.001"]}
						position={[0.01, 0.44, -1.21]}
						rotation={[1.86, -1.13, 3.08]}
					/>
					<mesh
						name="Sphere_39"
						geometry={nodes.Sphere_39.geometry}
						material={materials["Material.001"]}
						position={[-0.39, 0.24, -1.2]}
						rotation={[1.75, -0.06, 2.83]}
					/>
					<mesh
						name="Sphere_40"
						geometry={nodes.Sphere_40.geometry}
						material={materials["Material.001"]}
						position={[-0.72, 0.44, -0.98]}
						rotation={[0.92, -0.94, 2.01]}
					/>
					<mesh
						name="Sphere_41"
						geometry={nodes.Sphere_41.geometry}
						material={materials["Material.001"]}
						position={[-1.15, 0.44, -0.38]}
						rotation={[0.46, -0.4, 1.39]}
					/>
					<mesh
						name="Sphere_42"
						geometry={nodes.Sphere_42.geometry}
						material={materials["Material.001"]}
						position={[-1.26, 0.24, 0]}
						rotation={[Math.PI / 2, -0.19, Math.PI / 2]}
					/>
					<mesh
						name="Sphere_43"
						geometry={nodes.Sphere_43.geometry}
						material={materials["Material.001"]}
						position={[-1.15, 0.44, 0.38]}
						rotation={[0.49, 0.09, 1.14]}
					/>
					<mesh
						name="Sphere_44"
						geometry={nodes.Sphere_44.geometry}
						material={materials["Material.001"]}
						position={[-0.72, 0.44, 0.98]}
						rotation={[0.58, 0.72, 0.79]}
					/>
					<mesh
						name="Sphere_45"
						geometry={nodes.Sphere_45.geometry}
						material={materials["Material.001"]}
						position={[-0.39, 0.24, 1.2]}
						rotation={[1.39, -0.06, 0.31]}
					/>
					<mesh
						name="Sphere_46"
						geometry={nodes.Sphere_46.geometry}
						material={materials["Material.001"]}
						position={[0.01, 0.44, 1.21]}
						rotation={[1.19, 1.04, 0.05]}
					/>
					<mesh
						name="Sphere_47"
						geometry={nodes.Sphere_47.geometry}
						material={materials["Material.001"]}
						position={[0.71, 0.44, 0.99]}
						rotation={[2.39, 0.93, -1.3]}
					/>
					<mesh
						name="Sphere_48"
						geometry={nodes.Sphere_48.geometry}
						material={materials["Material.001"]}
						position={[1.02, 0.24, 0.74]}
						rotation={[1.46, 0.15, -0.93]}
					/>
					<mesh
						name="Sphere_49"
						geometry={nodes.Sphere_49.geometry}
						material={materials["Material.001"]}
						position={[1.16, 0.44, 0.37]}
						rotation={[2.59, 0.46, -1.69]}
					/>
					<mesh
						name="Sphere_50"
						geometry={nodes.Sphere_50.geometry}
						material={materials["Material.001"]}
						position={[0.39, 0.2, -1.21]}
						rotation={[1.69, 0.04, -2.83]}
					/>
					<mesh
						name="Sphere_51"
						geometry={nodes.Sphere_51.geometry}
						material={materials["Material.001"]}
						position={[0.39, -0.24, -1.2]}
						rotation={[0.94, 0.92, -2.62]}
					/>
					<mesh
						name="Sphere_52"
						geometry={nodes.Sphere_52.geometry}
						material={materials["Material.001"]}
						position={[-0.01, -0.44, -1.21]}
						rotation={[1.24, -0.16, -3.12]}
					/>
					<mesh
						name="Sphere_53"
						geometry={nodes.Sphere_53.geometry}
						material={materials["Material.001"]}
						position={[-1.03, 0.2, -0.75]}
						rotation={[1.65, -0.1, 2.2]}
					/>
					<mesh
						name="Sphere_54"
						geometry={nodes.Sphere_54.geometry}
						material={materials["Material.001"]}
						position={[-1.02, -0.24, -0.74]}
						rotation={[2.49, 0.62, 1.77]}
					/>
					<mesh
						name="Sphere_55"
						geometry={nodes.Sphere_55.geometry}
						material={materials["Material.001"]}
						position={[-1.16, -0.44, -0.37]}
						rotation={[1.31, 0.26, 1.97]}
					/>
					<mesh
						name="Sphere_56"
						geometry={nodes.Sphere_56.geometry}
						material={materials["Material.001"]}
						position={[-1.03, 0.2, 0.75]}
						rotation={[1.5, -0.1, 0.94]}
					/>
					<mesh
						name="Sphere_57"
						geometry={nodes.Sphere_57.geometry}
						material={materials["Material.001"]}
						position={[-1.02, -0.24, 0.74]}
						rotation={[2.57, -0.45, 1.08]}
					/>
					<mesh
						name="Sphere_58"
						geometry={nodes.Sphere_58.geometry}
						material={materials["Material.001"]}
						position={[-0.71, -0.44, 0.99]}
						rotation={[1.75, 0.33, 0.65]}
					/>
					<mesh
						name="Sphere_59"
						geometry={nodes.Sphere_59.geometry}
						material={materials["Material.001"]}
						position={[0.39, 0.2, 1.21]}
						rotation={[1.45, 0.04, -0.31]}
					/>
					<mesh
						name="Sphere_60"
						geometry={nodes.Sphere_60.geometry}
						material={materials["Material.001"]}
						position={[0.39, -0.24, 1.2]}
						rotation={[1.22, -1.02, -0.62]}
					/>
					<mesh
						name="Sphere_61"
						geometry={nodes.Sphere_61.geometry}
						material={materials["Material.001"]}
						position={[0.72, -0.44, 0.98]}
						rotation={[1.93, -0.06, -0.57]}
					/>
					<mesh
						name="Sphere_62"
						geometry={nodes.Sphere_62.geometry}
						material={materials["Material.001"]}
						position={[1.28, 0.2, 0]}
						rotation={[Math.PI / 2, 0.13, -Math.PI / 2]}
					/>
					<mesh
						name="Sphere_63"
						geometry={nodes.Sphere_63.geometry}
						material={materials["Material.001"]}
						position={[1.26, -0.24, 0]}
						rotation={[0.52, -0.09, -1.73]}
					/>
					<mesh
						name="Sphere_64"
						geometry={nodes.Sphere_64.geometry}
						material={materials["Material.001"]}
						position={[1.15, -0.44, -0.38]}
						rotation={[1.63, -0.36, -1.82]}
					/>
					<mesh
						name="Sphere_65"
						geometry={nodes.Sphere_65.geometry}
						material={materials["Material.001"]}
						position={[0.64, -0.83, -0.75]}
						rotation={[1.71, -1, -2.08]}
					/>
					<mesh
						name="Sphere_66"
						geometry={nodes.Sphere_66.geometry}
						material={materials["Material.001"]}
						position={[0.24, -1.02, -0.74]}
						rotation={[0.68, -0.25, -2.95]}
					/>
					<mesh
						name="Sphere_67"
						geometry={nodes.Sphere_67.geometry}
						material={materials["Material.001"]}
						position={[-0.08, -0.83, -0.99]}
						rotation={[0.67, -1.36, 2.96]}
					/>
					<mesh
						name="Sphere_68"
						geometry={nodes.Sphere_68.geometry}
						material={materials["Material.001"]}
						position={[-0.51, -0.83, -0.85]}
						rotation={[0.6, -0.34, 2.69]}
					/>
					<mesh
						name="Sphere_69"
						geometry={nodes.Sphere_69.geometry}
						material={materials["Material.001"]}
						position={[-0.63, -1.02, -0.46]}
						rotation={[0.91, 0.7, 2.45]}
					/>
					<mesh
						name="Sphere_70"
						geometry={nodes.Sphere_70.geometry}
						material={materials["Material.001"]}
						position={[-0.96, -0.83, -0.23]}
						rotation={[0.13, -0.14, 2.32]}
					/>
					<mesh
						name="Sphere_71"
						geometry={nodes.Sphere_71.geometry}
						material={materials["Material.001"]}
						position={[-0.96, -0.83, 0.23]}
						rotation={[0.77, 0.69, 1.92]}
					/>
					<mesh
						name="Sphere_72"
						geometry={nodes.Sphere_72.geometry}
						material={materials["Material.001"]}
						position={[-0.63, -1.02, 0.46]}
						rotation={[2.23, 0.7, 0.7]}
					/>
					<mesh
						name="Sphere_73"
						geometry={nodes.Sphere_73.geometry}
						material={materials["Material.001"]}
						position={[-0.51, -0.83, 0.85]}
						rotation={[0.29, 1.09, 2.04]}
					/>
					<mesh
						name="Sphere_74"
						geometry={nodes.Sphere_74.geometry}
						material={materials["Material.001"]}
						position={[0.91, -0.83, -0.38]}
						rotation={[0.58, -0.19, -2.35]}
					/>
					<mesh
						name="Sphere_75"
						geometry={nodes.Sphere_75.geometry}
						material={materials["Material.001"]}
						position={[0.78, -1.02, 0]}
						rotation={[-0.34, 0.41, -2.42]}
					/>
					<mesh
						name="Sphere_76"
						geometry={nodes.Sphere_76.geometry}
						material={materials["Material.001"]}
						position={[0.39, -1.23, 0]}
						rotation={[0.22, -0.56, -2.74]}
					/>
					<mesh
						name="Sphere_77"
						geometry={nodes.Sphere_77.geometry}
						material={materials["Material.001"]}
						position={[-0.08, -0.83, 0.99]}
						rotation={[2.25, 0.81, 0.06]}
					/>
					<mesh
						name="Sphere_78"
						geometry={nodes.Sphere_78.geometry}
						material={materials["Material.001"]}
						position={[0.24, -1.02, 0.74]}
						rotation={[2.46, -0.25, -0.19]}
					/>
					<mesh
						name="Sphere_79"
						geometry={nodes.Sphere_79.geometry}
						material={materials["Material.001"]}
						position={[0.64, -0.83, 0.75]}
						rotation={[2.96, 0.77, -0.71]}
					/>
				</group>
				<group name="Icosphere001">
					<mesh
						name="Sphere001"
						geometry={nodes.Sphere001.geometry}
						material={materials["Material.001"]}
						position={[0.01, -1, 0]}
						rotation={[-1.57, 0.01, 1.2]}
					/>
					<mesh
						name="Sphere001_1"
						geometry={nodes.Sphere001_1.geometry}
						material={materials["Material.001"]}
						position={[0.73, -0.44, 0.57]}
						rotation={[-2.5, -0.79, -2.65]}
					/>
					<mesh
						name="Sphere001_2"
						geometry={nodes.Sphere001_2.geometry}
						material={materials["Material.001"]}
						position={[-0.25, -0.46, 0.87]}
						rotation={[-2.63, 0.25, 3]}
					/>
					<mesh
						name="Sphere001_3"
						geometry={nodes.Sphere001_3.geometry}
						material={materials["Material.001"]}
						position={[-0.92, -0.45, -0.03]}
						rotation={[-1.48, 1.11, 1.46]}
					/>
					<mesh
						name="Sphere001_4"
						geometry={nodes.Sphere001_4.geometry}
						material={materials["Material.001"]}
						position={[-0.3, -0.46, -0.87]}
						rotation={[-0.48, 0.3, 0.15]}
					/>
					<mesh
						name="Sphere001_5"
						geometry={nodes.Sphere001_5.geometry}
						material={materials["Material.001"]}
						position={[0.7, -0.42, -0.51]}
						rotation={[-0.69, -0.8, -0.53]}
					/>
					<mesh
						name="Sphere001_6"
						geometry={nodes.Sphere001_6.geometry}
						material={materials["Material.001"]}
						position={[0.26, 0.42, 0.85]}
						rotation={[2.63, -0.28, 2.98]}
					/>
					<mesh
						name="Sphere001_7"
						geometry={nodes.Sphere001_7.geometry}
						material={materials["Material.001"]}
						position={[-0.73, 0.45, 0.52]}
						rotation={[2.4, 0.8, -2.56]}
					/>
					<mesh
						name="Sphere001_8"
						geometry={nodes.Sphere001_8.geometry}
						material={materials["Material.001"]}
						position={[-0.72, 0.47, -0.52]}
						rotation={[0.73, 0.83, -0.58]}
					/>
					<mesh
						name="Sphere001_9"
						geometry={nodes.Sphere001_9.geometry}
						material={materials["Material.001"]}
						position={[0.28, 0.44, -0.86]}
						rotation={[0.46, -0.29, 0.14]}
					/>
					<mesh
						name="Sphere001_10"
						geometry={nodes.Sphere001_10.geometry}
						material={materials["Material.001"]}
						position={[0.91, 0.44, 0.04]}
						rotation={[1.64, -1.1, 1.65]}
					/>
					<mesh
						name="Sphere001_11"
						geometry={nodes.Sphere001_11.geometry}
						material={materials["Material.001"]}
						position={[0, 0.99, 0]}
						rotation={[1.59, -0.03, 2.18]}
					/>
					<mesh
						name="Sphere001_12"
						geometry={nodes.Sphere001_12.geometry}
						material={materials["Material.001"]}
						position={[-0.16, -0.85, 0.5]}
						rotation={[-2.09, 0.17, 2.86]}
					/>
					<mesh
						name="Sphere001_13"
						geometry={nodes.Sphere001_13.geometry}
						material={materials["Material.001"]}
						position={[0.43, -0.85, 0.31]}
						rotation={[-1.93, -0.42, -2.32]}
					/>
					<mesh
						name="Sphere001_14"
						geometry={nodes.Sphere001_14.geometry}
						material={materials["Material.001"]}
						position={[0.26, -0.54, 0.79]}
						rotation={[-2.53, -0.26, -2.96]}
					/>
					<mesh
						name="Sphere001_15"
						geometry={nodes.Sphere001_15.geometry}
						material={materials["Material.001"]}
						position={[0.85, -0.56, 0.02]}
						rotation={[-1.55, -1.01, -1.55]}
					/>
					<mesh
						name="Sphere001_16"
						geometry={nodes.Sphere001_16.geometry}
						material={materials["Material.001"]}
						position={[0.43, -0.87, -0.28]}
						rotation={[-1.23, -0.44, -0.88]}
					/>
					<mesh
						name="Sphere001_17"
						geometry={nodes.Sphere001_17.geometry}
						material={materials["Material.001"]}
						position={[-0.51, -0.84, 0.01]}
						rotation={[-1.57, 0.53, 1.57]}
					/>
					<mesh
						name="Sphere001_18"
						geometry={nodes.Sphere001_18.geometry}
						material={materials["Material.001"]}
						position={[-0.71, -0.52, 0.49]}
						rotation={[-2.31, 0.77, 2.49]}
					/>
					<mesh
						name="Sphere001_19"
						geometry={nodes.Sphere001_19.geometry}
						material={materials["Material.001"]}
						position={[-0.18, -0.85, -0.48]}
						rotation={[-1.09, 0.19, 0.35]}
					/>
					<mesh
						name="Sphere001_20"
						geometry={nodes.Sphere001_20.geometry}
						material={materials["Material.001"]}
						position={[-0.67, -0.52, -0.52]}
						rotation={[-0.81, 0.76, 0.63]}
					/>
					<mesh
						name="Sphere001_21"
						geometry={nodes.Sphere001_21.geometry}
						material={materials["Material.001"]}
						position={[0.23, -0.56, -0.82]}
						rotation={[-0.59, -0.27, -0.18]}
					/>
					<mesh
						name="Sphere001_22"
						geometry={nodes.Sphere001_22.geometry}
						material={materials["Material.001"]}
						position={[0.95, 0.01, 0.3]}
						rotation={[3.1, -1.25, 3.1]}
					/>
					<mesh
						name="Sphere001_23"
						geometry={nodes.Sphere001_23.geometry}
						material={materials["Material.001"]}
						position={[0.96, -0.02, -0.31]}
						rotation={[-0.08, -1.25, -0.07]}
					/>
					<mesh
						name="Sphere001_24"
						geometry={nodes.Sphere001_24.geometry}
						material={materials["Material.001"]}
						position={[0.03, 0.01, 1.04]}
						rotation={[3.12, -0.04, 3.14]}
					/>
					<mesh
						name="Sphere001_25"
						geometry={nodes.Sphere001_25.geometry}
						material={materials["Material.001"]}
						position={[0.59, 0.01, 0.81]}
						rotation={[3.11, -0.63, 3.12]}
					/>
					<mesh
						name="Sphere001_26"
						geometry={nodes.Sphere001_26.geometry}
						material={materials["Material.001"]}
						position={[-0.95, 0, 0.31]}
						rotation={[3.09, 1.28, -3.09]}
					/>
					<mesh
						name="Sphere001_27"
						geometry={nodes.Sphere001_27.geometry}
						material={materials["Material.001"]}
						position={[-0.62, 0.02, 0.82]}
						rotation={[3.1, 0.64, -3.12]}
					/>
					<mesh
						name="Sphere001_28"
						geometry={nodes.Sphere001_28.geometry}
						material={materials["Material.001"]}
						position={[-0.59, 0.01, -0.81]}
						rotation={[0.02, 0.65, -0.01]}
					/>
					<mesh
						name="Sphere001_29"
						geometry={nodes.Sphere001_29.geometry}
						material={materials["Material.001"]}
						position={[-0.93, -0.01, -0.3]}
						rotation={[0.04, 1.25, -0.04]}
					/>
					<mesh
						name="Sphere001_30"
						geometry={nodes.Sphere001_30.geometry}
						material={materials["Material.001"]}
						position={[0.59, 0, -0.81]}
						rotation={[-0.02, -0.62, -0.01]}
					/>
					<mesh
						name="Sphere001_31"
						geometry={nodes.Sphere001_31.geometry}
						material={materials["Material.001"]}
						position={[-0.02, 0, -0.98]}
						rotation={[0.01, 0, 0]}
					/>
					<mesh
						name="Sphere001_32"
						geometry={nodes.Sphere001_32.geometry}
						material={materials["Material.001"]}
						position={[0.71, 0.49, 0.49]}
						rotation={[2.36, -0.75, 2.55]}
					/>
					<mesh
						name="Sphere001_33"
						geometry={nodes.Sphere001_33.geometry}
						material={materials["Material.001"]}
						position={[-0.24, 0.54, 0.78]}
						rotation={[2.52, 0.24, -2.98]}
					/>
					<mesh
						name="Sphere001_34"
						geometry={nodes.Sphere001_34.geometry}
						material={materials["Material.001"]}
						position={[-0.85, 0.51, 0.01]}
						rotation={[1.57, 1.04, -1.57]}
					/>
					<mesh
						name="Sphere001_35"
						geometry={nodes.Sphere001_35.geometry}
						material={materials["Material.001"]}
						position={[-0.26, 0.53, -0.82]}
						rotation={[0.55, 0.25, -0.15]}
					/>
					<mesh
						name="Sphere001_36"
						geometry={nodes.Sphere001_36.geometry}
						material={materials["Material.001"]}
						position={[0.69, 0.52, -0.5]}
						rotation={[0.83, -0.76, 0.64]}
					/>
					<mesh
						name="Sphere001_37"
						geometry={nodes.Sphere001_37.geometry}
						material={materials["Material.001"]}
						position={[0.14, 0.84, 0.5]}
						rotation={[2.12, -0.16, 2.89]}
					/>
					<mesh
						name="Sphere001_38"
						geometry={nodes.Sphere001_38.geometry}
						material={materials["Material.001"]}
						position={[0.52, 0.84, 0.02]}
						rotation={[1.6, -0.55, 1.62]}
					/>
					<mesh
						name="Sphere001_39"
						geometry={nodes.Sphere001_39.geometry}
						material={materials["Material.001"]}
						position={[-0.43, 0.85, 0.31]}
						rotation={[1.93, 0.44, -2.29]}
					/>
					<mesh
						name="Sphere001_40"
						geometry={nodes.Sphere001_40.geometry}
						material={materials["Material.001"]}
						position={[-0.4, 0.88, -0.34]}
						rotation={[1.22, 0.41, -0.84]}
					/>
					<mesh
						name="Sphere001_41"
						geometry={nodes.Sphere001_41.geometry}
						material={materials["Material.001"]}
						position={[0.16, 0.85, -0.5]}
						rotation={[1.05, -0.19, 0.33]}
					/>
				</group>
				<mesh
					name="Sphere003"
					geometry={nodes.Sphere003.geometry}
					material={materials["Material.002"]}
					position={[0.28, -3.84, 3.84]}
					rotation={[-2.36, 1.52, Math.PI]}
				/>
				<mesh
					name="Sphere002"
					geometry={nodes.Sphere002.geometry}
					material={materials["Material.002"]}
					position={[0.29, 1.22, 4.52]}
					rotation={[2.88, 1.51, Math.PI]}
				/>
				<mesh
					name="Sphere007"
					geometry={nodes.Sphere007.geometry}
					material={materials["Material.002"]}
					position={[-0.11, 3.85, -3.85]}
					rotation={[0.79, -1.55, 0]}
				/>
				<mesh
					name="Sphere008"
					geometry={nodes.Sphere008.geometry}
					material={materials["Material.002"]}
					position={[5.39, 0.54, -0.54]}
					rotation={[-2.36, -0.14, -Math.PI / 2]}
				/>
				<mesh
					name="Sphere004"
					geometry={nodes.Sphere004.geometry}
					material={materials["Material.002"]}
					position={[-5.42, -0.3, 0.3]}
					rotation={[Math.PI / 4, 0.08, 0]}
				/>
				<mesh
					name="Sphere005"
					geometry={nodes.Sphere005.geometry}
					material={materials["Material.002"]}
					position={[-0.53, -1.22, -4.5]}
					rotation={[-0.26, -1.46, 0]}
				/>
				<mesh
					name="Sphere006"
					geometry={nodes.Sphere006.geometry}
					material={materials["Material.002"]}
					position={[4.74, -3.95, -1.01]}
					rotation={[-1.32, 0.71, Math.PI]}
				/>
				<mesh
					name="Sphere009"
					geometry={nodes.Sphere009.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					name="Sphere010"
					geometry={nodes.Sphere010.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					name="Sphere011"
					geometry={nodes.Sphere011.geometry}
					material={materials["Material.002"]}
					position={[0.39, -6.04, -1.54]}
					rotation={[-1.32, 1.51, -Math.PI]}
				/>
				<mesh
					name="Sphere012"
					geometry={nodes.Sphere012.geometry}
					material={materials["Material.002"]}
					position={[4.71, 3.97, 1.01]}
					rotation={[-1.32, -0.72, Math.PI]}
				/>
				<mesh
					name="Sphere013"
					geometry={nodes.Sphere013.geometry}
					material={materials["Material.002"]}
					position={[-6.22, -0.53, -0.14]}
					rotation={[1.82, 0.09, 0]}
				/>
				<mesh
					name="Sphere014"
					geometry={nodes.Sphere014.geometry}
					material={materials["Material.002"]}
					position={[-4.25, -4.44, -1.13]}
					rotation={[1.82, 0.82, 0]}
				/>
				<mesh
					name="Sphere015"
					geometry={nodes.Sphere015.geometry}
					material={materials["Material.002"]}
					position={[6.26, 0, 0]}
					rotation={[-1.32, 0, -Math.PI]}
				/>
				<mesh
					name="Sphere016"
					geometry={nodes.Sphere016.geometry}
					material={materials["Material.002"]}
					position={[-0.16, 6.06, 1.54]}
					rotation={[1.82, -1.55, 0]}
				/>
				<mesh
					name="Sphere017"
					geometry={nodes.Sphere017.geometry}
					material={materials["Material.002"]}
					position={[-4.71, 3.97, 1.01]}
					rotation={[1.82, -0.72, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/reaction.1.glb");
